"use strict";
const $ = (id) => document.getElementById(id);
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let state = null, page = "overview", selectedCommand = null, selectedPath = null, selectedPreview = null, inspectingFolder = false, pendingUnpack = null, polling = false, clockAnchor = null, renderSignature = null, bundlePathsInitialized = false, foldersInitialized = false;
const monotonic = () => globalThis.performance?.now?.() ?? Date.now();
function syncClock(now) { if(clockAnchor===null)clockAnchor={server:now,local:monotonic()}; }
function clockSeconds() { return clockAnchor ? clockAnchor.server+(monotonic()-clockAnchor.local)/1000 : Date.now()/1000; }
function renderIfChanged() { const {now,token,...stable}=state; const signature=JSON.stringify(stable);if(signature!==renderSignature){renderSignature=signature;render();} }
const active = c => ["RUNNING", "STOPPING", "CANCELLING"].includes(c.status);
const titles = {overview:"Workspace overview", runner:"Runner & watcher", scheduler:"Dependency scheduler", tools:"Bundles & EGP", history:"Run history", files:"Files & folders"};
function duration(seconds) { if (seconds == null || !Number.isFinite(Number(seconds))) return "—"; seconds = Math.max(0, Math.floor(seconds)); return `${String(Math.floor(seconds/3600)).padStart(2,"0")}:${String(Math.floor(seconds%3600/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`; }
function elapsed(item) { return item.status === "UNKNOWN" ? "—" : active(item) && item.started ? duration(clockSeconds() - item.started) : duration(item.elapsed); }
function timer(item) { return `<span class="elapsed" ${active(item)&&item.started?`data-start="${Number(item.started)}"`:""}>${elapsed(item)}</span>`; }
function date(value) { return value ? new Date(Number(value)*1000).toLocaleString([], {month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}) : "—"; }
function badge(status, override) { const label = {CANCELLED:"Stopped by you",CANCELLING:"Stopping file",RUNNING:"Running",STOPPING:"Finishing files",STOPPED:"Stopped",STOPPED_ON_ERROR:"Stopped after error",SUCCESS:"Success",FAILED:"Failed",SAS_ERROR:"SAS error",CONNECTION_LOST:"Connection lost",ALWAYS_RUN_DEFINITION:"Shared setup",PENDING:"Pending",BLOCKED_DEPENDENCY:"Blocked",SKIPPED_SUCCESS:"Skipped",SKIPPED_PREVIOUS:"Previously completed",UNKNOWN:"Unknown"}[status] || status; const cls = active({status})?"running": status.includes("SUCCESS")||status==="SKIPPED_PREVIOUS"?"success":/FAIL|ERROR|LOST|BLOCKED/.test(status)?"error":status==="PENDING"?"pending":""; return `<span class="badge ${cls}">${esc(override || label)}</span>`; }
function empty(title, text) { return `<div class="empty"><span class="empty-icon" aria-hidden="true">◇</span><strong>${esc(title)}</strong><p>${esc(text)}</p></div>`; }
function table(headers, rows) { return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`; }
async function api(path, data) { const response = await fetch(path, data === undefined ? {} : {method:"POST",headers:{"Content-Type":"application/json","X-PySAS-Token":state?.token || ""},body:JSON.stringify(data)}); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Request failed"); return result; }
function error(message) { $("error").textContent = message; $("error").hidden = !message; }
function navigate(next) { page = titles[next] ? next : "overview"; document.querySelectorAll(".page").forEach(p=>p.hidden = p.id !== `page-${page}`); document.querySelectorAll(".nav").forEach(n=>{n.classList.toggle("active", n.dataset.page===page); if(n.dataset.page===page)n.setAttribute("aria-current","page");else n.removeAttribute("aria-current");}); $("page-title").textContent=titles[page]; history.replaceState(null,"",`#${page}`); render(); }
function fillSelect(select, values) { const signature = JSON.stringify(values); if (select.dataset.signature === signature) return; const current=select.value, first=select.options[0]?.textContent || "Select a file"; select.innerHTML=`<option value="">${esc(first)}</option>` + values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join(""); if(values.includes(current))select.value=current; select.dataset.signature=signature; }
function files() { if(state.folders && !foldersInitialized){for(const key of ["inputs","init","inbox"])$("folder-"+key).value=state.folders[key];foldersInitialized=true;}const settings=state.bundle_settings || {paths:[],last:""};fillSelect($("saved-bundle-path"),settings.paths);if(!bundlePathsInitialized){$("bundle-code-root").value=settings.last;$("saved-bundle-path").value=settings.paths.includes(settings.last)?settings.last:"";bundlePathsInitialized=true;} document.querySelectorAll("select[data-files]").forEach(s=>fillSelect(s,state.files.filter(f=>f.toLowerCase().endsWith("."+s.dataset.files)))); fillSelect($("previous-schedule"),state.history.filter(h=>h.kind==="schedule"&&h.status!=="UNKNOWN").map(h=>h.path)); }
function taskScope(task) {
  const parts=[];
  if(task.section)parts.push(`Section ${task.section}`);
  const first=Number(task.row_start)||0,last=Number(task.row_end)||0;
  if(first&&last)parts.push(first===last?`Row ${first}`:`Rows ${first}–${last}`);
  else if(first)parts.push(`From row ${first} to end`);
  else if(last)parts.push(`Rows 1–${last}`);
  else if(!task.section&&(Object.prototype.hasOwnProperty.call(task,"row_start")||Object.prototype.hasOwnProperty.call(task,"row_end")))parts.push("Whole program");
  return parts.join(" · ");
}
function taskTable(tasks, commandId) { return table(["File / task","Status","Elapsed",""], tasks.map(t=>`<tr><td>${esc(t.name)}${taskScope(t)?`<small class="task-scope">${esc(taskScope(t))}</small>`:""}${t.kind==="task"?`<small>${esc(t.key)}${t.depends_on?.length?` · After ${esc(t.depends_on.join(", "))}`:""}</small>`:""}${t.setup?.length?`<small>Shared setup: ${t.setup.map(s=>esc(s.program)+(taskScope(s)?` (${esc(taskScope(s))})`:"" )).join(" → ")}</small>`:""}${t.progress&&["RUNNING","CANCELLING"].includes(t.status)?`<small class="task-progress">${esc(t.progress)}</small>`:""}${t.message?`<small>${esc(t.message)}</small>`:""}</td><td>${badge(t.status)}</td><td>${timer(t)}</td><td>${t.path?`<button class="subtle" data-path="${esc(t.path)}">Inspect →</button>`:""}${t.status==="RUNNING"&&t.can_cancel_file!==false&&t.path&&(t.command_id||commandId)?`<button class="subtle" title="Stop this file; partial SAS outputs may remain" data-cancel-command="${esc(t.command_id||commandId)}" data-cancel-key="${esc(t.key)}">Stop file</button>`:""}</td></tr>`)); }
function live() { const tasks=state.commands.filter(active).flatMap(c=>Object.values(c.tasks).filter(t=>["RUNNING","CANCELLING"].includes(t.status)).map(t=>({...t,command_id:c.id}))); return tasks.length?taskTable(tasks):empty("No files running", "Start a program, a watcher, or a schedule to see live elapsed time here."); }
function historyTable(records) { return records.length?table(["File / run","Status","Started","Elapsed",""],records.map(h=>`<tr><td>${esc(h.name)}<small>${h.kind==="schedule"?`Schedule${h.tasks!=null?` · ${h.tasks} tasks`:""}`:esc(h.path)}</small></td><td>${badge(h.status)}</td><td>${date(h.started)}</td><td>${timer(h)}</td><td><button class="subtle" data-path="${esc(h.path)}">Inspect →</button></td></tr>`)):empty("No saved runs yet", "Completed SAS files and schedules will appear here with their logs and results."); }
function scheduleStopControl(command) {
  if(!command || !["schedule","continue"].includes(command.action) || !active(command))return "";
  const stopping=command.status==="STOPPING";
  return `<button class="subtle" data-stop-schedule="${esc(command.id)}" ${stopping?"disabled":""} title="Stop this entire schedule and its active files">${stopping?"Stopping schedule…":"Stop schedule"}</button>`;
}
function commandCards(commands, showTasks=false) { if(!commands.length)return empty("No command activity", "Commands launched from this workbench will appear here.");return commands.map(c=>`<article class="command-card"><div class="command-head"><div><strong>${esc(c.name)}</strong>${badge(c.status,c.status==="STOPPING"&&["schedule","continue"].includes(c.action)?"Stopping schedule":null)}${timer(c)}<small>${date(c.started)}${c.code_root?` · ${esc(c.code_root)}`:""}</small></div>${scheduleStopControl(c)}<button class="subtle" data-command="${esc(c.id)}">Console →</button></div>${c.message?`<p class="empty-small">${esc(c.message)}</p>`:""}${c.download?`<a class="subtle" href="/api/download?command=${encodeURIComponent(c.id)}" download>Download bundle ↓</a>`:""}${showTasks&&Object.keys(c.tasks).length?taskTable(Object.values(c.tasks),c.id):""}</article>`).join(""); }
function render() { if(!state)return;$("watch-inbox-path").textContent=state.folders?.inbox || "runner/inbox";$("keep-awake").checked=!!state.awake?.enabled;$("keep-awake").disabled=!state.awake?.supported;$("awake-status").textContent=state.awake?.error || (state.awake?.enabled?"On · Windows and display idle sleep are prevented.":state.awake?.supported?"Off · Normal power settings apply.":"Available on Windows. No mouse or keyboard input is generated.");uploadDestination(); const watcher=state.commands.find(c=>c.action==="watch"&&active(c)); $("running-count").textContent=state.commands.filter(active).flatMap(c=>Object.values(c.tasks).filter(t=>t.status==="RUNNING")).length; $("queue-count").textContent=state.queued.length; $("completed-count").textContent=state.history.filter(h=>!["RUNNING","UNKNOWN"].includes(h.status)).length; $("watcher-state").textContent=watcher?(watcher.status==="STOPPING"?"Finishing":"Watching"):"Stopped"; $("watcher-time").innerHTML=watcher?`${timer(watcher)} · ${watcher.status==="STOPPING"?"Waiting for active files":"Session elapsed"}`:"Ready when you are"; $("start-watch").disabled=!!watcher||!state.windows; $("stop-watch").disabled=!watcher||watcher.status==="STOPPING";
if(page==="overview"){$("live-overview").innerHTML=live();$("recent-runs").innerHTML=historyTable(state.history.slice(0,6));$("commands-overview").innerHTML=commandCards(state.commands.slice(0,5));}
if(page==="runner"){$("init-file-list").innerHTML=state.initialization_files?.length?state.initialization_files.map(p=>`<div class="queue-item"><code>${esc(p)}</code></div>`).join(""):'<p class="hint">No _*.sas files were found in the initialization folder or inbox.</p>';$("live-runner").innerHTML=live();$("inbox").innerHTML=state.queued.length?state.queued.map((name,i)=>`<div class="queue-item"><span class="badge pending">${i+1}</span><span>${esc(name)}</span><small>Waiting</small></div>`).join(""):'<p class="hint">The inbox is empty. Add job .sas files through Files & folders or your configured inbox.</p>';}
if(page==="scheduler")$("schedule-activity").innerHTML=commandCards(state.commands.filter(c=>["schedule","continue"].includes(c.action)).slice(0,10),true);
if(page==="tools")$("tools-activity").innerHTML=commandCards(state.commands.filter(c=>c.action.startsWith("bundle-")||c.action.startsWith("egp-")).slice(0,10));
if(page==="history"){let records=state.history;const q=$("history-search").value.toLowerCase(), filter=$("history-filter").value;records=records.filter(h=>(h.name+" "+h.path).toLowerCase().includes(q)&&(filter==="all"||filter==="errors"&&/FAIL|ERROR|LOST|BLOCKED/.test(h.status)||h.status===filter));$("all-history").innerHTML=historyTable(records);$("commands-history").innerHTML=commandCards(state.commands);}}
async function refresh(force=false) { if(polling)return; polling=true;try{state=await api(force?"/api/state?refresh=1":"/api/state");if($("error").textContent.startsWith("The local server is unavailable"))error("");syncClock(state.now);$("workspace").textContent=state.workspace;$("version").textContent=`v${state.version} · This computer only`;$("connection").textContent="Connected locally";$("connection-dot").className="online";const notices=[];if(!state.windows)notices.push("SAS execution requires Windows with Enterprise Guide. You can use file tools and inspect history on this computer.");if(!state.openpyxl)notices.push("Install openpyxl for schedules and Excel table previews (see START_HERE.txt).");$("notice").textContent=notices.join(" ");$("notice").hidden=!notices.length;document.querySelectorAll(".sas-action").forEach(b=>b.disabled=!state.windows);files();renderIfChanged();if($("details-dialog").open){if(selectedCommand)await refreshConsole();else if(inspectingFolder&&selectedPath)await showPath(selectedPath,true);}}catch(e){$("connection").textContent="Connection lost";$("connection-dot").className="offline";error("The local server is unavailable. The app may have closed. Displayed job states may be stale.");}finally{polling=false;}}
function formData(form) { const data=Object.fromEntries(new FormData(form));form.querySelectorAll('input[type="checkbox"]').forEach(c=>data[c.name]=c.checked);return data; }
async function launch(data, form) { const button=form?.querySelector('[type="submit"]');if(button)button.disabled=true;error("");try{const result=await api("/api/launch",data);await refresh();await showCommand(result.id);}catch(e){error(e.message);}finally{if(button)button.disabled=false;}}
function bindForm(id, action) { $(id).addEventListener("submit",event=>{event.preventDefault();launch({...formData(event.currentTarget),action},event.currentTarget);}); }
function openDialog(title) { $("detail-title").textContent=title;$("detail-tasks").innerHTML="";$("file-list").innerHTML="";$("preview-name").textContent="Select a file";$("download").hidden=true;$("file-preview").innerHTML="";if(!$("details-dialog").open)$("details-dialog").showModal(); }
async function showCommand(identifier) { inspectingFolder=false;selectedPreview=null;selectedCommand=identifier;selectedPath=null;const command=state.commands.find(c=>c.id===identifier);openDialog(command?.name || "Command output");$("detail-meta").textContent=command?`py pysas.py ${command.args.join(" ")}`:"";$("preview-name").textContent="Console output";$("file-list").innerHTML='<p class="hint">The console updates while this command is running. SAS logs and results become available as Enterprise Guide writes them.</p>';await refreshConsole(); }
async function refreshConsole() { const id=selectedCommand;try{const result=await api(`/api/console?id=${encodeURIComponent(id)}`);if(selectedCommand!==id)return;const command=state.commands.find(c=>c.id===id);if(command?.download)$("file-list").innerHTML=`<a class="primary" href="/api/download?command=${encodeURIComponent(id)}" download>Download bundle ↓</a>`;$("detail-tasks").innerHTML=scheduleStopControl(command)+(command&&Object.keys(command.tasks).length?taskTable(Object.values(command.tasks),id):"");const panel=$("file-preview"), atEnd=panel.scrollHeight-panel.scrollTop-panel.clientHeight<80;if(panel.dataset.output!==result.text){panel.dataset.output=result.text;panel.innerHTML=`<pre>${esc(result.text)}</pre>`;}if(atEnd)panel.scrollTop=panel.scrollHeight;}catch(e){error(e.message);}}
async function showPath(path, updating=false) { if(!updating){selectedPreview=null;selectedCommand=null;selectedPath=path;inspectingFolder=true;openDialog(path.split(/[\\/]/).pop());$("detail-meta").textContent=path;$("file-preview").innerHTML='<p class="empty-small">Loading run files…</p>';}try{const detail=await api(`/api/details?path=${encodeURIComponent(path)}`);if(selectedPath!==path)return;const groups={Logs:[],Code:[],Results:[],"Run files":[]};detail.files.forEach(f=>{const ext=f.name.toLowerCase();const group=ext.endsWith(".log")?"Logs":ext.endsWith(".sas")?"Code":/[\\/]results[\\/]/.test("/"+ext)?"Results":"Run files";groups[group].push(f);});$("file-list").innerHTML=Object.entries(groups).filter(([,v])=>v.length).map(([name,list])=>`<div class="file-category">${name}</div>${list.map(f=>`<button class="file-item" data-preview="${esc(f.path)}">${esc(f.name)}</button>`).join("")}`).join("")||'<p class="hint">Waiting for output. This inspector refreshes automatically.</p>';if(detail.tasks.length)$("detail-tasks").innerHTML=taskTable(detail.tasks.map(t=>({...t,key:t.task_id,name:t.program,kind:"task",depends_on:t.depends_on?t.depends_on.split(","):[]})));const first=detail.files.find(f=>f.path===selectedPreview)||detail.files.find(f=>f.name.endsWith(".log"))||detail.files.find(f=>f.name.endsWith(".txt"))||detail.files[0];if(first)await preview(first.path,updating);else $("file-preview").innerHTML='<p class="empty-small">No output files have been written yet.</p>';}catch(e){$("file-preview").textContent=e.message;}}
async function preview(path, updating=false) { selectedPreview=path;const panel=$("file-preview"),scroll=panel.scrollTop,atEnd=panel.scrollHeight-panel.scrollTop-panel.clientHeight<80; $("preview-name").textContent=path.split(/[\\/]/).pop();$("download").href=`/api/download?path=${encodeURIComponent(path)}`;$("download").hidden=false;document.querySelectorAll(".file-item").forEach(b=>b.classList.toggle("selected",b.dataset.preview===path));if(!updating)$("file-preview").textContent="Loading preview…";const expected=$("download").href;try{const result=await api(`/api/preview?path=${encodeURIComponent(path)}`);if($("download").href!==expected)return;if(result.modified)$("preview-name").textContent=`${path.split(/[\\/]/).pop()} · updated ${new Date(result.modified*1000).toLocaleTimeString()}`;if(updating&&!result.sheets&&panel.dataset.output===result.text)return;if(result.sheets){$("file-preview").innerHTML=`<p class="hint">${esc(result.note)}</p>`+result.sheets.map(sheet=>`<h3>${esc(sheet.name)}</h3>${table((sheet.rows[0]||[]).map(esc),sheet.rows.slice(1).map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join("")}</tr>`))}`).join("");}else{panel.dataset.output=result.text;$("file-preview").innerHTML=`<pre>${result.text.split("\n").map(line=>/^\s*ERROR/i.test(line)?`<span class="log-error">${esc(line)}</span>`:/^\s*WARNING/i.test(line)?`<span class="log-warning">${esc(line)}</span>`:esc(line)).join("\n")}</pre>`;}if(updating)panel.scrollTop=atEnd?panel.scrollHeight:scroll;}catch(e){$("file-preview").textContent=e.message;}}
function toolFields(){const bundle=$("bundle-action").value;$("bundle-input-label").hidden=bundle==="bundle-pack";$("bundle-output-label").hidden=bundle!=="bundle-pack";$("recursive-label").hidden=bundle!=="bundle-pack";const egp=$("egp-action").value;$("egp-source-label").hidden=egp!=="egp-pack";$("egp-output-label").hidden=egp==="egp-inspect";}
document.addEventListener("click",async e=>{const button=e.target.closest("button");if(!button)return;if(button.dataset.page)navigate(button.dataset.page);if(button.dataset.go)navigate(button.dataset.go);if(button.dataset.command)await showCommand(button.dataset.command);if(button.dataset.path)await showPath(button.dataset.path);if(button.dataset.preview)await preview(button.dataset.preview);});
bindForm("run-form","run");bindForm("watch-form","watch");bindForm("schedule-form","schedule");bindForm("continue-form","continue");
$("stop-watch").addEventListener("click",async()=>{const watcher=state.commands.find(c=>c.action==="watch"&&active(c));if(!watcher)return;try{await api("/api/stop",{id:watcher.id});await refresh();}catch(e){error(e.message);}});
$("bundle-form").addEventListener("submit",e=>{e.preventDefault();const data=formData(e.currentTarget);if(data.action==="bundle-unpack"){pendingUnpack=data;$("unpack-target").textContent=`Restore into: ${data.code_root || state.workspace}`;$("confirm-dialog").showModal();}else launch(data,e.currentTarget);});
$("confirm-unpack").addEventListener("click",()=>{$("confirm-dialog").close();launch(pendingUnpack,$("bundle-form"));pendingUnpack=null;});$("cancel-unpack").addEventListener("click",()=>{$("confirm-dialog").close();pendingUnpack=null;});
$("egp-form").addEventListener("submit",e=>{e.preventDefault();const data=formData(e.currentTarget);if(data.action==="egp-pack")data.template=data.project;launch(data,e.currentTarget);});
$("preview-schedule").addEventListener("click",async()=>{const path=$("schedule-form").elements.workbook.value;if(!path){error("Select a schedule workbook first.");return;}inspectingFolder=false;selectedCommand=null;selectedPath=path;openDialog("Schedule workbook");$("detail-meta").textContent=path;await preview(path);});
$("close-details").addEventListener("click",()=>$("details-dialog").close());$("details-dialog").addEventListener("close",()=>{selectedCommand=null;selectedPath=null;});
$("bundle-action").addEventListener("change",toolFields);$("egp-action").addEventListener("change",toolFields);$("history-search").addEventListener("input",render);$("history-filter").addEventListener("change",render);$("refresh").addEventListener("click",()=>{error("");refresh(true);});
function tick(){$("clock").textContent=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"});if($("connection-dot").className!=="online")return;document.querySelectorAll("[data-start]").forEach(el=>{const value=duration(clockSeconds()-Number(el.dataset.start));if(el.textContent!==value)el.textContent=value;});}
toolFields();navigate(location.hash.slice(1)||"overview");refresh();tick();setInterval(refresh,2000);setInterval(tick,200);

// Optional read-only integration for browsers that expose a page tool registry.
if (document.modelContext?.registerTool) {
  const lifecycle = new AbortController();
  window.addEventListener("pagehide", () => lifecycle.abort(), {once:true});
  try {
    Promise.resolve(document.modelContext.registerTool({
      name: "inspect_pysas_runs",
      title: "Inspect PySAS runs",
      description: "Read running filenames, job statuses, elapsed seconds, and recent completed runs in this local workspace. Does not start or stop jobs.",
      inputSchema: {type:"object", properties:{limit:{type:"integer",minimum:1,maximum:50}}, additionalProperties:false},
      annotations: {readOnlyHint:true, untrustedContentHint:true},
      async execute(input) {
        if (!input || typeof input!=="object" || Array.isArray(input) || Object.keys(input).some(k=>k!=="limit")) throw new Error("Expected an object with an optional limit.");
        const limit=input.limit ?? 10;
        if(!Number.isInteger(limit)||limit<1||limit>50)throw new Error("Limit must be between 1 and 50.");
        const snapshot=await api("/api/state");
        return {running:snapshot.commands.filter(active).flatMap(c=>Object.values(c.tasks).filter(t=>t.status==="RUNNING").map(t=>({name:t.name,status:t.status,elapsed_seconds:Math.max(0,snapshot.now-t.started)}))),recent:snapshot.history.slice(0,limit).map(h=>({name:h.name,status:h.status,elapsed_seconds:h.elapsed,path:h.path}))};
      }
    },{signal:lifecycle.signal})).catch(()=>{});
  } catch (_) { /* Standard browsers work without a tool registry. */ }
}

$("saved-bundle-path").addEventListener("change",()=>{$("bundle-code-root").value=$("saved-bundle-path").value;$("bundle-path-status").textContent="Pack, verify and unpack will use this code folder.";});
$("save-bundle-path").addEventListener("click",async()=>{try{const settings=await api("/api/bundle-paths",{operation:"save",path:$("bundle-code-root").value});$("bundle-code-root").value=settings.last;state.bundle_settings=settings;files();$("saved-bundle-path").value=settings.last;$("bundle-path-status").textContent="Path saved. It will be available next time you open the workbench.";}catch(e){error(e.message);}});
$("remove-bundle-path").addEventListener("click",async()=>{const path=$("saved-bundle-path").value;if(!path)return;try{state.bundle_settings=await api("/api/bundle-paths",{operation:"remove",path});files();$("bundle-path-status").textContent="Saved shortcut removed. No folders or files were deleted.";}catch(e){error(e.message);}});

function uploadDestination(){const target=$("upload-target").value || "inputs";$("upload-folder").textContent="Destination: "+(target==="bundle"?($("bundle-code-root").value||state?.workspace||"Workspace"):state?.folders?.[target]||"Workspace");}
$("upload-target").addEventListener("change",uploadDestination);
$("folders-form").addEventListener("submit",async e=>{e.preventDefault();error("");try{const saved=await api("/api/folders",formData(e.currentTarget));state.folders=saved;for(const key of ["inputs","init","inbox"])$("folder-"+key).value=saved[key];$("folders-status").textContent="Folder settings saved.";await refresh();}catch(e){error(e.message);}});
$("keep-awake").addEventListener("change",async()=>{try{state.awake=await api("/api/awake",{enabled:$("keep-awake").checked});render();}catch(e){error(e.message);$("keep-awake").checked=!!state?.awake?.enabled;}});
function uploadFile(file,target){return new Promise((resolve,reject)=>{const request=new XMLHttpRequest();const query=new URLSearchParams({target,name:file.name});if(target==="bundle")query.set("code_root",$("bundle-code-root").value);request.open("POST","/api/upload?"+query);request.setRequestHeader("X-PySAS-Token",state.token);request.upload.onprogress=e=>{if(e.lengthComputable)$("upload-progress").value=e.loaded/e.total*100;};request.onload=()=>{let result;try{result=JSON.parse(request.responseText);}catch(_){reject(new Error("The upload server returned an invalid response."));return;}if(request.status>=200&&request.status<300)resolve(result);else reject(new Error(result.error||"Upload failed"));};request.onerror=()=>reject(new Error("The upload connection was interrupted."));request.send(file);});}
$("upload-form").addEventListener("submit",async e=>{e.preventDefault();const files=Array.from($("upload-files").files);if(!files.length)return;const target=$("upload-target").value;const button=e.currentTarget.querySelector('[type="submit"]');button.disabled=true;$("upload-progress").hidden=false;const outcomes=[];try{for(const file of files){$("upload-status").textContent=`Uploading ${file.name}…`;$("upload-progress").value=0;try{await uploadFile(file,target);outcomes.push(`${file.name}: uploaded`);}catch(e){outcomes.push(`${file.name}: ${e.message}`);}}$("upload-status").textContent=outcomes.join("\n");await refresh();}finally{button.disabled=false;$("upload-progress").hidden=true;}});

$("quit-app").addEventListener("click",async()=>{try{await api("/api/quit",{});$("notice").hidden=false;$("notice").textContent="PySAS is closing after active jobs finish. You can close this window.";}catch(e){error(e.message);}});

document.addEventListener("click",async event=>{const button=event.target.closest("[data-cancel-command]");if(!button)return;button.disabled=true;try{await api("/api/cancel-file",{id:button.dataset.cancelCommand,key:button.dataset.cancelKey});await refresh();}catch(e){error(e.message);button.disabled=false;}});

document.addEventListener("click",async event=>{const button=event.target.closest("[data-stop-schedule]");if(!button)return;button.disabled=true;try{await api("/api/stop",{id:button.dataset.stopSchedule});await refresh();}catch(e){error(e.message);button.disabled=false;}});
